[tool.poetry]
name = "tailr_backend"
version = "0.1.0"
description = ""
authors = ["Matias Perichon <matias.perichon@hotmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
graphene = ">=3.0"
flask = "^3.0.3"